### ISSUE TITLE
Readme code doesn't work: "xenserver_vdi.vdi: Unable to parse XenAPI response"

### ISSUE THREAD

**Issue by holmesb** [ringods/terraform-provider-xenserver#12]
[The readme example code](https://github.com/ringods/terraform-provider-xenserver) fails for me:
```
provider "xenserver" {
    url = "${var.xenserver_url}"
    username = "${var.xenserver_username}"
    password = "${var.xenserver_password}"
}

resource "xenserver_vdi" "vdi" {
  sr_uuid = "<my_sr_uuid>"
  name_label = "test vdi"
  size = 1073741824 # 1GB
}

resource "xenserver_network" "net" {
  name_label = "vm only network"
  bridge = "xapi1"
  description = "this will create VM-only network"
}

resource "xenserver_vm" "web" {
    name_label = "web"
    base_template_name = "<my_template_name>"
    static_mem_min = 2147483648 # 2GB
    static_mem_max = 2147483648
    dynamic_mem_min = 2147483648
    dynamic_mem_max = 2147483648
    boot_order = "cdn"
    network_interface {
        network_uuid = "${xenserver_network.net.id}
        mac = "12:34:45:67:89:12"
        mtu = 1500
        device = 0
    }
    vcpus = 2
    cdrom {
      vdi_uuid = "<my_iso_uuid>"
    }
    hard_drive {
      vdi_uuid = "${xenserver_vdi.vdi.id}"
    }
}
```
I assumed that the two network_interfaces defined in the xenserver_vm block was unintentional.  I'm running XenServer v7.1
Error is:

> Error applying plan:
> 
> 1 error(s) occurred:
> 
> * xenserver_vdi.vdi: 1 error(s) occurred:
> 
> * xenserver_vdi.vdi: Unable to parse XenAPI response: got value "vdi_mirror" for enum StorageOperations at SR.get_record -> .allowed_operations[9], but this is not any of the known values
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.

**Comment by mborodin** [comment]
Hi,
XenServer 7.2 introduced new possible StorageOperations. Fix is submitted to ringods/go-xen-api-client#6

**Comment by ajagnanan** [comment]
I tried updated to the latest master with https://github.com/ringods/terraform-provider-xenserver/pull/14 merged in, but this seems to still be happening. I did have the previous version installed, is there something I'm missing?

**Comment by mborodin** [comment]
@ajagnanan can you show output of terraform with TF_LOG=DEBUG?

**Comment by ajagnanan** [comment]
Thanks for that option, it was locked to the previous version still. Works now 👍

**Comment by ringods** [comment]
@ajagnanan then I'm going to close this issue. If you encounter other problems, please file a new issue.
