### ISSUE TITLE
Gitter channel?

### ISSUE THREAD

**Issue by briantopping** [ringods/terraform-provider-xenserver#20]
Are there enough people using this (and the Xen connector) to warrant a single channel on Gitter? If folks aren't already on Gitter, that can be annoying, but sometimes people have questions that are too simple for creating an issue over and might lose interest as a result? 

Just thinking out loud, but it might provide cues as to where to improve. Or it might just be a PITA :-)

**Comment by ringods** [comment]
@briantopping I have moderate time to maintain this. I will not be able to participate there (a lot).

Looking a the Github download statistics on the README file, not a lot of people are using this at the moment. Adding a Gitter channel will probably only lead to more frustration: you ask a question, but hardly anybody will respond. People usually have expectations of fast feedback on such a synchronous channel. Less so by using issues IMO.

**Comment by briantopping** [comment]
Yes I think that makes good sense. It should be fun for everyone! :)
