### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by oogali** [ringods/terraform-provider-xenserver#8]
I see that the latest commit to this repository (as of today) was 12 days ago, but the latest release is from March 2016.

Could you cut a new release and upload to Github?

**Comment by ringods** [comment]
@oogali the original author of this code, @amfranz, doesn't have the time anymore to maintain this. So far, I have merged all contributions living in forks into this repository, but there is still more work to do before it can be used alongside Terraform 0.10.x.

For the time being, help is welcome to compile it from source, test it and fix bugs.

**Comment by ringods** [comment]
@oogali I have spent the day setting up to produce Github releases via Travis CI.

Here are some new binaries: [v0.2.0](https://github.com/ringods/terraform-provider-xenserver/releases/tag/v0.2.0)
